### PR TITLE
[Merged by Bors] - chore: update version

### PR DESCRIPTION
**Pull request by morenol**

### CODE REVIEW

**Review by EstebanBorai — APPROVED** [review]

**Comment by morenol** [comment]
I see that in this repo, we don't perform any cloud related test. So the tests that we currenyly have should be run as part of PR CIs, the issue is that we are calling `fluvio cloud login` before them and I think that it is not needed. I will create a PR removing that step to see if CI is green after that

**Comment by EstebanBorai** [comment]
> I see that in this repo, we don't perform any cloud related test. So the tests that we currenyly have should be run as part of PR CIs, the issue is that we are calling `fluvio cloud login` before them and I think that it is not needed. I will create a PR removing that step to see if CI is green after that

SGTM! Im still have to setup integration tests here!

**Comment by EstebanBorai** [comment]
Tracking for Integration Tests: https://github.com/infinyon/sql-connector/issues/9

**Pull request closed without merging**
