### PR TITLE
test: dont login on cloud for CI tests

### PR DESCRIPTION
**Pull request by morenol**

### CODE REVIEW

**Review by EstebanBorai — APPROVED** [review]
Good catch!

**Comment by morenol** [comment]
@EstebanBorai this is failing due to :

```
    `fluvio hub download` failed with:
     Hub error: downloading infinyon/json-sql@0.1.0
    Server: Read error /home/runner/.fluvio/logins/current
```

**Comment by galibey** [comment]
that login was needed for being able to download smartmodule, if we remove it, need to build manually and load smartmodule to the cluster

**Comment by sehz** [comment]
We should avoid dependency to cloud for integration test

**Comment by galibey** [comment]
> We should avoid dependency to cloud for integration test

Ok, then we need to migrate `json-sql` smartmodule to this repo. It doesn't have a "home" yet, so works out perfectly.

**Comment by ozgrakkurt** [comment]
closing this, I'll open another PR that implements it

**Comment by ozgrakkurt** [comment]
https://github.com/infinyon/sql-connector/pull/88

**Pull request closed without merging**
